In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
import math
df.bedrooms = df.bedrooms.fillna(round(df.bedrooms.mean()))

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

In [9]:
reg.predict([[3000,3,40]])

/opt/homebrew/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [10]:
reg.predict([[2500,4,5]])

/opt/homebrew/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

## Predict salary based on experience, test and interview score

In [11]:
df1 = pd.read_csv('hiring_candidate.csv')

In [12]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
from word2number import w2n

In [14]:
def convert2num(col):
    for i in range(len(col)):
        if col[i] is np.nan:
            col[i] = 0
        else:
            col[i] = w2n.word_to_num(col[i])
            
convert2num(df1.experience)

/var/folders/c_/bmbgzh1n0z7806c46lty6r9c0000gn/T/ipykernel_828/1683458653.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  col[i] = 0
/var/folders/c_/bmbgzh1n0z7806c46lty6r9c0000gn/T/ipykernel_828/1683458653.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  col[i] = w2n.word_to_num(col[i])


In [15]:
df1.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: object

In [16]:
df1['test_score(out of 10)'].fillna(0,inplace=True)

In [17]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    0.0                           7      72000
7         11                    7.0                           8      80000

In [18]:
reg1 = linear_model.LinearRegression()
reg.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

LinearRegression()

In [19]:
reg.coef_

array([3077.8642085 ,  999.7856246 , 2118.48834717])

In [20]:
reg.predict([[2,9,6]])

/opt/homebrew/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52688.25222797])

In [21]:
reg.predict([[12,12,10]])

/opt/homebrew/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([94940.20457538])

In [22]:
reg.intercept_

24823.523106605804

In [23]:
3077.8642085*12 + 999.7856246*12 + 2118.48834717*10 + 24823.523106605804

94940.2045755058